### ISSUE TITLE
why not using zookeeper watch?

### ISSUE THREAD

**Issue by likebean** [officedrop/jedis_failover#1]
Hi,in ZooKeeperNetworkClient.java using timer to get clusterData ,why not using zookeeper watch ?  
   this.timer = new Timer(true);
            this.timer.scheduleAtFixedRate(new TimerTask() {
                @Override
                public void run() {
                    ClusterStatus clusterStatus = getClusterData();

```
                if (clusterStatus != null && !clusterStatus.equals(ZooKeeperNetworkClient.this.lastClusterStatus)) {
                    ZooKeeperNetworkClient.this.lastClusterStatus = clusterStatus;
                    clusterStatusChanged();
                }

            }
        }, 0, 5000);
```

**Comment by mauricio** [comment]
Using watches was causing the client to go out of memory due to too many watches being triggered at the same time. AFAIK it was a bug in the Netflix Curator framework that eventually got fixed after this was placed in production.

Since this is a much simpler solution that also happens to cause less overhead on clients and servers, I don't see why change it back to use watches.
